#spring.main.allow-circular-references = true
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/first_db
#spring.datasource.username=first_user
#spring.datasource.password=root
#spring.main.allow-circular-references=true



spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.open-in-view=true

spring.jpa.hibernate.ddl-auto=update
